networks:
  keys:
    driver: bridge

services:
  app:
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - keys
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      HTTP_ADDR: ":8080"
      DEBUG_ERRORS: 1
      DSN: "mysql:password@tcp(mysql:3306)/licenses?parseTime=true"
      MIGRATIONS_PATH: "file://migrations"

  mysql:
    restart: always
    image: mysql:latest
    networks:
      - keys
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=licenses
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 10
